repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--target-version=py311, --line-length=120]
        stages: [commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--line-length=120]
        stages: [commit]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming, flake8-import-order]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args: [src/]
        pass_filenames: false

      - id: pytest-fast
        name: pytest (fast)
        entry: poetry run pytest tests/ -x --tb=short
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: compression-test
        name: compression round-trip test
        entry: ./test_compression.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: pytest-coverage
        name: pytest with coverage
        entry: poetry run pytest tests/ -v --cov=src/tdd_ai_py --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: black-check
        name: black (check)
        entry: poetry run black --check src/ tests/
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: isort-check
        name: isort (check)
        entry: poetry run isort --check-only src/ tests/
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: flake8-check
        name: flake8
        entry: poetry run flake8 src/ tests/
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: mypy-check
        name: mypy
        entry: poetry run mypy src/
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
